server:
  port: 8081
  servlet:
    session:
      timeout: 30m
    context-path: /
  tomcat:
    uri-encoding: utf-8
    max-thread: 500
info:
  app:
    encoding: @project.build.sourceEncoding@
    app:
      java:
        source: @java.version@
        target: @java.version@
    author:
      name: zhangwei
      email: zhangweicalm@gmail.com
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  thymeleaf:
    cache: false #是否开启缓存，默认为true，开发时设置为false
    check-template: true #检查模板是否存在，默认为true
    check-template-location: true #检查模板位置是否存在，默认为true
    encoding: UTF-8 #模板文件编码
    prefix: classpath:/templates/ #模板文件位置
    servlet:
      content-type: text/html #Content-Type配置
    suffix: .html #模板文件后缀
  mvc:
    view:
      prefix: /
      suffix: .html
#  activemq:
#    broker-url: tcp://localhost:61616 #activeMq
#    packages:
#      trust-all: true #信任所有的包
#    user: admin
#    password: admin
management: #actualtor配置
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST
  endpoint:
    health:
      show-details: when_authorized
      roles: ADMIN

d3:
  kml_root: /Users/weizhang/d3-kml/